# Generated by Django 4.0.2 on 2023-08-25 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('preview_link', models.TextField(blank=True, max_length=255, null=True)),
                ('details_link', models.TextField(blank=True, max_length=500, null=True)),
                ('script_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('ratingCount', models.IntegerField(blank=True, null=True)),
                ('salesCount', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('lastUpdate', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=255)),
                ('script', models.ForeignKey(default='script', on_delete=django.db.models.deletion.CASCADE, related_name='description', to='theme.script')),
            ],
        ),
    ]
